"""Global constants for Ad-Leak-Engine [SEED: 2399]."""
SEED_NUMBER = 2399
ENGINE_NAME = "Ad-Leak-Engine"
ENGINE_VERSION = "0.1.0"

CREATIVE_FATIGUE_DAYS = 30
MIN_AB_VARIATION_ADS = 3
SPEND_WITHOUT_TESTING_USD = 1000.0
SPEND_WITHOUT_TESTING_MIN_ADS = 5

LCP_MOBILE_THRESHOLD_MS = 2500
TTFB_THRESHOLD_MS = 800
TAP_TARGET_MIN_PX = 48
CHECKOUT_MAX_STEPS = 4
PIXEL_BLOCKING_SCRIPTS_MAX = 5

HIGH_CONFIDENCE_MIN_SIGNALS = 2
LOW_CONFIDENCE_THRESHOLD = 0.5

CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_RECOVERY_SECONDS = 300
PROXY_COOLDOWN_SECONDS = 600
